config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'contact/index'


  get 'about/index'
  get 'dev/fun'
  root 'welcome#index'

  get 'profile/:username', to: 'profiles#show', as: :profile
  get 'profile/:username/edit', to: 'profiles#edit', as: :edit_profile
  patch 'profile/:username/edit', to: 'profiles#update', as: :update_profile



  resources :styles do
    resources :pictures
    resources :comments
  end
  get 'about' => 'about#index'
  get 'contact' => 'contact#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :style
end

app/models/picture.rb
class Picture < ApplicationRecord
	belongs_to :style
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>", normalermodus: "400x400", testen: "500x500^" }, :default_url => "/assets/images/:style/missing.png"
 	do_not_validate_attachment_file_type :image, content_type: /\Aimage\/.*\z/
end

app/models/style.rb
class Style < ApplicationRecord
	has_many :pictures, :dependent => :destroy
	has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, styles: { 
    img: "200x200#",
    info: "300x300#"
    }, default_url: "missing.png"
  do_not_validate_attachment_file_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :comments, dependent: :destroy
  has_many :styles, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      	where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end

    end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_styles

	def index
		@comments = @style.comments.order('created_at asc')
	end
	def create
		@comment = @style.comments.build(comment_params)
		@comment.user_id = current_user.id
		@comment.user_name = current_user.username
		if @comment.save
			redirect_to @style
			else
			redirect_to root_path 
		end
	end
	def destroy
		@comment = @style.comments.find(params[:id])
		if @comment.user_id == current_user.id
			@comment.destroy
			redirect_to @style
		end
	end
	def show
	end

	def comment_params
		params.require(:comment).permit(:content, :username)
	end
	def set_styles
		@style = Style.find(params[:style_id])
	end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/dev_controller.rb
class DevController < ApplicationController
  def fun
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

def new
	@style = Style.find(params[:styles_id])
	@pictures = @style.pictures.build
end

def create
	@pictures = Pictures.new(params[:pictures])
	if @pictures.save
		puts "Pictures Saved"
	else
		redirect_to @style
	end
end

def show
	@pictures = Picture.find(params[:id])
end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
	def index
		@styles = Style.all
	end
	def new
		@style = current_user.styles.build
	end
	def create
		@style = current_user.styles.build(style_params)
		@style.user_name = current_user.username
 		if @style.save
 			if params[:images]
 				params[:images].each do |image|
 					@style.pictures.create(image: image)
 				end
 			end
		end
		redirect_to @style
	end
	
	def show
  		@style = Style.find(params[:id])
  		@pictures = @style.pictures
  	end
  	def edit
  		@style = Style.find(params[:id])
  		@style.save
  	end
  	def destroy
  		@style = Style.find(params[:id])
		@style.destroy
		redirect_to styles_path
  	end

private

  	def style_params
    params.require(:style).permit(:title, :text, :pictures)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
		case level
			when :notice then "alert alert-info"
			when :success then "alert alert-success"
			when :error then "alert alert-error"
			when :alert then "alert alert-error"
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dev_helper.rb
module DevHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>MAXIMUS</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		
		<style>
			
		</style>
	</head>

	<body>
		<nav class="navbar navbar-fixed-top navbar-inverse">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand" href="/">MAXIMUS</a>
				</div>
					<!-- Menu Items -->
				<div id="navbar" class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li><a href="/styles">Fashion</a></li>
						<li><a href="/about">About</a></li>
						<li><a href="/contact">Contact</a></li>
						<li><a href="/users/edit">Edit</a></li>
					</ul>
					<form class="navbar-form navbar-right">
						<% if user_signed_in? %>
							<%= link_to "Logout", destroy_user_session_path, :method => :delete,
							:class => 'btn btn-info'%>
						<% else %>
							<!-- Modal -->
							<%= link_to :new_user_registration do %>
								<button type="button" class="btn btn-primary" href="/users/sign_in">Register</button>
							<% end %>
							<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#login">Login</button>
						<% end %>
					</form>
				</div>
			</div>
		</nav>
		
		<% if flash[:notice] %>
			<div class="notifications">
				<p class=" alert alert-info"><%= notice %></p>
			</div>
		<% end %>
		
		<%= render file: "share/loginpopup.html.erb" %>
		<% form_for(:user, url: user_session_path) do |i|%>
			<% i.label :username, :class => 'nav navbar-nav' %>
		<% end %>

		<!-- Pop Ups -->


		<%= yield %>
	</body>
</html>
<!-- Following Page Content -->

app/views/share/loginpopup.html.erb
<div class="modal fade" id="login" role="dialog" data-keyboard="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Login</h4>
      </div>
        <div class="modal-body">
          <%= form_for(:user, :url => session_path(:user)) do |f| %>
            <%= f.label :Username %>
            <br>
            <%= f.text_field :login %>
            <br>
            <br>
            <%= f.label :password%>
            <br>
            <%= f.password_field :password %>
            <br>
            <%= f.submit 'Sign in' %>
            <%= link_to "or Register", new_user_registration_path(), :class => 'btn btn-info' %>
            <br>
            <%= link_to "Forgot your password?", new_password_path(:user) %>
          <% end %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
  </div>
</div>

app/views/share/registerpopup.html.erb
<div class="modal fade" id="register" role="dialog" data-keyboard="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Register to MAXIMUS</h4>
			</div>
				<div class="modal-body">
					<%= form_for(:user, :url => registration_path(:user)) do |f| %>
						<%= f.label :Email %>
						<%= f.text_field :email %>
						<br>
						<%= f.label :Username %>
						<%= f.text_field :username %>
						<br>
						<%= f.label :Password %>
						<%= f.password_field :password %>
						<br>
						<%= f.check_box :remember_me %>
						<%= f.label :remember_me %>
						<br>
						<%= f.submit 'Register' %>
					<% end %>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
		</div>
	</div>
</div>