config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'contact/index'


  get 'about/index'
  get 'dev/fun'
  root 'welcome#index'

  get 'profile/:username', to: 'profiles#show', as: :profile
  get 'profile/:username/edit', to: 'profiles#edit', as: :edit_profile
  patch 'profile/:username/edit', to: 'profiles#update', as: :update_profile



  resources :styles do
    resources :pictures
    resources :comments
  end
  get 'about' => 'about#index'
  get 'contact' => 'contact#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :style
end

app/models/picture.rb
class Picture < ApplicationRecord
	belongs_to :style
	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>", normalermodus: "400x400", testen: "500x500^" }, :default_url => "/assets/images/:style/missing.png"
 	do_not_validate_attachment_file_type :image, content_type: /\Aimage\/.*\z/
end

app/models/style.rb
class Style < ApplicationRecord
	has_many :pictures, :dependent => :destroy
	has_many :comments, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :avatar, styles: { 
    img: "200x200#",
    info: "300x300#"
    }, default_url: "missing.png"
  do_not_validate_attachment_file_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :comments, dependent: :destroy
  has_many :styles, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  attr_accessor :login

  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      	where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_h).first
      end

    end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#before_action :configuring, if: :devise_controller?

#######--- Aktuelle Seite Speichern ---#######

protected


private

def save_page
    store_location_for(:user, request.url)
end

def after_sign_out_path_for(resource)
    request.referrer || root_path
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_styles

	def index
		@comments = @style.comments.order('created_at asc')
	end
	def create
		@comment = @style.comments.build(comment_params)
		@comment.user_id = current_user.id
		@comment.user_name = current_user.username
		if @comment.save
			redirect_to @style
			else
			redirect_to root_path 
		end
	end
	def destroy
		@comment = @style.comments.find(params[:id])
		if @comment.user_id == current_user.id
			@comment.destroy
			redirect_to @style
		end
	end
	def show
	end

	def comment_params
		params.require(:comment).permit(:content, :username)
	end
	def set_styles
		@style = Style.find(params[:style_id])
	end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/dev_controller.rb
class DevController < ApplicationController
  def fun
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

def new
	@style = Style.find(params[:styles_id])
	@pictures = @style.pictures.build
end

def create
	@pictures = Pictures.new(params[:pictures])
	if @pictures.save
		puts "Pictures Saved"
	else
		redirect_to @style
	end
end

def show
	@pictures = Picture.find(params[:id])
end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_user
	before_action :owned_profile, only: [:edit, :update]

	def show
		if @user
			if user_signed_in?
				if current_user == @user
					@own_profile = true
					else
					@own_profile = false
				end
				else
				@own_profile = false
			end
			if @user.styles.exists?
				@posts = @user.styles
				else
				@posts = nil
			end
		end
	end

	def edit
	end

	def update
		if @user.update(profile_params)
			flash[:success] = "Dein Profil wurde geändert!"
			redirect_to profile_path(@user.username)
		else
			flash[:alert] = "ERROR!"
			redirect_to contact_path
		end
	end

	private
	
	def profile_params
		params.require(:user).permit(:avatar, :status)
	end	
	
	def set_user
		@user = User.find_by(username: params[:username])
	end

	def owned_profile
		unless current_user == @user
			redirect_to root_path
			flash[:alert] = "Das ist nicht dein Profil! Du Schwanzus Longus!"
		end
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :status, :avatar)
  end

  def account_update_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :status, :avatar)
  end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
	def index
		@styles = Style.all
	end
	def new
		@style = current_user.styles.build
	end
	def create
		@style = current_user.styles.build(style_params)
		@style.user_name = current_user.username
 		if @style.save
 			if params[:images]
 				params[:images].each do |image|
 					@style.pictures.create(image: image)
 				end
 			end
		end
		redirect_to @style
	end
	
	def show
  		@style = Style.find(params[:id])
  		@pictures = @style.pictures
  	end
  	def edit
  		@style = Style.find(params[:id])
  		@style.save
  	end
  	def destroy
  		@style = Style.find(params[:id])
		@style.destroy
		redirect_to styles_path
  	end

private

  	def style_params
    params.require(:style).permit(:title, :text, :pictures)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
		case level
			when :notice then "alert alert-info"
			when :success then "alert alert-success"
			when :error then "alert alert-error"
			when :alert then "alert alert-error"
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dev_helper.rb
module DevHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/show.html.erb
<center>
<h3>Author</h3>
<%= @comment.user_name %>
<br>
<%= @comment.content %>
</center>

app/views/styles/edit.html.erb
<%= form_for :styles, url: styles_path, html: { multipart: true } do |f| %>
  <p>
      <%= f.label :title %><br>
      <%= f.text_field :title, :value => :title %>
    </p>
 
    <%= f.file_field :image %>
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>
 
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/styles/index.html.erb
<head>
	<%= stylesheet_link_tag "slideshow" %>
	<%= stylesheet_link_tag "styles" %>
	<title>All Styles</title>
	</head>
<body>

<div class="gallery">
	<% @styles.each do |style| %>
		<% if style.user_name == "Florin" %>
			<div class="col-md-4">
				<%= link_to style do%>
						<div 
							class="thumbnail original" 
							data-top="background-color:rgb(255,255,255);"
							data--500-top="background-color:rgb(200,200,200);">
							<div class="caption">
	   		    				<center>
	   		    					<h3 class="heading"><%= style.title %></h3>
	   		    				</center>
	   		    				<%= image_tag "qualle.png", class: "qualle" %>
	    					</div>
							<% if style.pictures.first %>
								<%= link_to image_tag(style.pictures.first.image.url(:medium)), style_path(style)%>
								<% else %>
								<center><h1>No Photos found</h1></center>
							<% end %>
							<%= link_to "Delete", style, :method => :delete %>
						</div>
					</div>
				<% end %>
			</div>
			
			<% else %>
			<div class="col-md-4">
				<%= link_to style do%>
					<div class="thumbnail user_post" 
						data-top="background-color:rgb(255,255,255);"
						data--500-top="background-color:rgb(200,200,200);">
						<div class="caption">
	   		    			<center><h3 class="heading"><%= style.title %></h3></center>
	    				</div>
						<% if style.pictures.first %>
							<%= link_to image_tag(style.pictures.first.image.url(:medium)), style_path(style)%>
							<% else %>
							<center><h1>No Photos found</h1></center>
						<% end %>
						<%= link_to "Delete", style, :method => :delete %>
					</div>
				<% end %>
			</div>
		<% end %>
	<% end %>
</div>



<script type="text/javascript" src="skrollr.min.js"></script>
    <script type="text/javascript">
    var s = skrollr.init();
</script>
</body>

app/views/styles/new.html.erb
 <head>
<title>New Style</title>
</head>
<body>
<center>
<% if user_signed_in? %>
  <%= form_for @style, :html => { multipart: true } do |f| %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>
    <%= file_field_tag "images[]", type: :file, multiple: true %>
    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text %>
    </p>
 
    <p>
      <%= f.submit %>
    </p>
  <% end %>
  <% else %>
    <h1>Please Login First</h1>
<% end %>
</center>
</body>

app/views/styles/show.html.erb
<script type="text/javascript" src="slideshow.js"></script>
<%= stylesheet_link_tag "slideshow" %>
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

<center>
<h1>
  <%= @message %>
</h1>
 
<h1><b>
<%= @style.title %>
</b></h1>
<h4>
  <%= @style.text %>
</h4>

</center>



<div class="slideshow">
	<center>
		<% @pictures.each_with_index do |pic, index| %>
    	    <% if index == 0 %>
    	    	<center>
    	    	<%= image_tag pic.image.url(:testen), :class => "slide js-fade fade-in", :style => "display: block;", :align =>"middle" %>
    	    	</center>
    	    <% else %>
    	    	<center>
    	    	<%= image_tag pic.image.url(:testen), :class => "slide js-fade fade-in", :align => "middle" %>
    	    	</center>
    	    <% end %>
    	<% end %>

		<%= image_tag "pfeil- links.png", :class => "arrow arrow_left", :onclick => "plusSlides(-1)"%>
    	<%= image_tag "pfeil- rects.png", :class => "arrow arrow_right", :onclick => "plusSlides(1)" %>
    </center>
</div>




<div class="action-area">
	<center>
		<% if user_signed_in? %>
			<%= form_for [@style, @style.comments.new] do |i| %>
				<%= i.text_field :content, placeholder: 'Write a Comment...' %>
				<%= i.submit %>
			<% end %>
		<% else %>
			<br>
			<a data-toggle="modal" style="cursor:pointer" data-target="#login">Login to write a Comment</a>
		<% end %>

	</center>
</div>



<div class="comment-area">
	
	<div class="comment-header-font">
		<p class="comment-font">Comments</p>
	</div>


	<% @style.comments.each do |commy| 
		if !commy.content.nil? %>
			<div class="comment">
				<div class="comment-head">
					<a class="comment-head-name"><%= commy.user_name %></a>
					</div>
					<%= commy.content %>
					<% if user_signed_in? %>
						<% if current_user.id == commy.user_id %>
						<%= link_to style_comment_path(@style, commy), :method => :delete do %>
									<remove class="remove-comment">X</remove>
							<% end
						end
					end %>
				</div>
			</div>
		<% end
	end %>


</div>